name: Actions Timeline Test

on:
  push:

jobs:
  actions-timeline:
    runs-on: ubuntu-latest
    #needs: [test-job1, test-job2]
    steps:
      - uses: Kesin11/actions-timeline@v2

  test-job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Command
        run: |
          echo "This is a test command."
          sleep 5
          echo "Command completed successfully."

      - name: Run Another Command
        run: |
          echo "This is another command."
          asleep 2

      - name: Loop Command
        run: |
          for i in {1..10}; do
            echo "Iteration $i"
            sleep 1
          done

  test-job2:
    runs-on: ubuntu-latest
    needs: test-job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Job 1 Command
        run: |
          echo "This is Job 1 command."
          sleep 3
          echo "Job 1 completed successfully."

  #actions-timeline:
  #  runs-on: ubuntu-latest
  #  needs: [test-job1, test-job2]
  #  steps:
  #    - uses: Kesin11/actions-timeline@v2
